version: '3.9'

services:
  database:
    build: ./postgres
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./java-hello
    container_name: my-springboot-container
    depends_on:
      - database
    networks:
      - app-network

  httpd:
    build: ./http-server
    container_name: my-http-container
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:

volumes:
  pgdata:

