#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/launch_proxy
- name: Launch httpd proxy container
  docker_container:
    name: proxy
    image: xiangtong/tp-devops-httpd:latest
    ports:
      - "80:80"
    networks:
      - name: my_app_net
    state: started
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python

