#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/launch_database
- name: Launch Postgres container
  docker_container:
    name: postgres
    image: xiangtong/tp-devops-database:latest
    pull: always
    env:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    networks:
      - name: my_app_net
    state: started
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python

